version: "3.8"
name: "mathusha"

services:
  api:
    container_name: "backend"
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "50051:50051"
